services:
  reverse-proxy:
    image: nginx:alpine
    ports:
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./certs:/etc/nginx/certs
    networks:
      net:
        aliases:
          - auth.test.local

  authelia:
    image: authelia/authelia
    volumes:
      - ./authelia:/config
    networks:
    - net

  mongodb:
    image: mongo:8
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - mongo_data:/data/db
    networks:
      - net

  rocketchat:
    build:
      context: .
      dockerfile: rocketchat/Dockerfile
    environment:
      MONGO_URL: mongodb://mongodb:27017/rocketchat?replicaSet=rs0
      ROOT_URL: https://rocket.test.local
      PORT: 3000
    secrets:
      - rocketchat_oidc_secret
    depends_on:
      - mongodb
    networks:
      - net

  confluence:
    build:
      context: .
      dockerfile: confluence/Dockerfile
    secrets:
      - confluence_oidc_secret
    depends_on:
      - postgres-confluence
    volumes:
      - confluence_data:/var/atlassian/application-data/confluence
    networks:
      - net
  postgres-confluence:
    image: postgres:16
    restart: unless-stopped
    environment:
      - POSTGRES_DB=confluence
      - POSTGRES_USER=confluence
      - POSTGRES_PASSWORD=confluencepassword
    volumes:
      - confluence_pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - net
networks:
  net:

volumes:
  mongo_data:
  confluence_data:
  confluence_pg_data:
secrets:
  rocketchat_oidc_secret:
    file: ./secrets/rocketchat_oidc_secret
  confluence_oidc_secret:
    file: ./secrets/confluence_oidc_secret