server {
    listen 443 ssl;
    server_name auth.test.local;
    ssl_certificate     /etc/nginx/certs/_wildcard.test.local.pem;
    ssl_certificate_key /etc/nginx/certs/_wildcard.test.local-key.pem;

    location / {
        proxy_pass http://authelia:9091; # les communications entre conteneurs sont en http
        proxy_set_header Host $host; # authelia vérifie que la req vient de domain = auth.test.local
        proxy_set_header X-Forwarded-Proto https;  # toujours en https
        proxy_set_header X-Forwarded-Host $host; 
    }
}

server {
    listen 443 ssl;
    server_name jenkins.test.local;
    ssl_certificate     /etc/nginx/certs/_wildcard.test.local.pem;
    ssl_certificate_key /etc/nginx/certs/_wildcard.test.local-key.pem;

    location / {
        proxy_pass http://jenkins:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto https;
    }
}

server {
    listen 443 ssl;
    server_name gitlab.test.local;
    ssl_certificate     /etc/nginx/certs/_wildcard.test.local.pem;
    ssl_certificate_key /etc/nginx/certs/_wildcard.test.local-key.pem;
    
    location / {
        proxy_pass http://gitlab:80;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto https;
    }    
}

#server {
#    listen 443 ssl;
#    server_name app.test.local;
#    ssl_certificate     /etc/nginx/certs/_wildcard.test.local.pem;
#    ssl_certificate_key /etc/nginx/certs/_wildcard.test.local-key.pem;

    # avant de servir la page, verifier que l'user est auth
#    location /authelia {
#        internal; #l'user ne peut pas ya accéder directement avec requete externe
#        proxy_pass http://authelia:9091/api/authz/forward-auth; # authelia verifie le cookie 
#        proxy_set_header X-Forwarded-Method $request_method;
#        proxy_set_header X-Forwarded-Proto https; # authelia n'accepte pas de traffic http
#        proxy_set_header X-Forwarded-Host $host;   
#        proxy_set_header X-Forwarded-URI $request_uri; # pour le ?rd= 
#    }

#    location / {
#        auth_request /authelia;
#        auth_request_set $target_url $upstream_http_location;# set le lien de redirection
#        error_page 401 = @authelia_redirect; # auth_request reçoit un 401 ou 500 
#        error_page 500 = @authelia_redirect;
#        
#        root /usr/share/nginx/html;# l'app est la page par défaut de nginx
#    }
    
#    location @authelia_redirect {
#        return 302 $target_url; # redirection vers auth.test.local avec le paramètre rd=
#    }
#}

